### ISSUE TITLE
[Proposal] Add replicas/updatedReplicas/availableReplicas/unavailableReplicas to job status

### ISSUE THREAD

**Issue by ghost** [AliyunContainerService/kubernetes-cronhpa-controller#142]
It'll be quite useful to add these information to those scalable objects. e.g.,

```yaml
apiVersion: autoscaling.alibabacloud.com/v1beta1
kind: CronHorizontalPodAutoscaler
metadata:
  name: foo
  namespace: testing
spec:
  jobs:
  - name: job1
    schedule: 0 03 18 * * *
    targetSize: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dep1
status:
  conditions:
  - jobId: ee23a447-a173-43eb-a400-77398c4bc0f4
    lastProbeTime: "2024-08-11T10:03:00Z"
    message: xxxx
    name: job1
    runOnce: false
    schedule: 0 03 18 * * *
    state: Succeed
    targetSize: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dep1
```

![image](https://github.com/user-attachments/assets/12db2ac8-eabb-457a-82df-3ee2af3f891b)
