### ISSUE TITLE
The cronhpa is still scaled using the schedule field defined in the previous job

### ISSUE THREAD

**Issue by Belyenochi** [AliyunContainerService/kubernetes-cronhpa-controller#27]
[env]
kubernetes version 1.13.2
[description]
The cronhpa is still scaled using the schedule field defined in the previous job

Repeat step:
1. kubectl create -f xxx.yaml
```
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment-basic
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9 # replace it with your exactly <image_name:tags>
        ports:
        - containerPort: 80
---
apiVersion: autoscaling.alibabacloud.com/v1beta1
kind: CronHorizontalPodAutoscaler
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cronhpa-sample
spec:
   scaleTargetRef:
      apiVersion: apps/v1beta2
      kind: Deployment
      name: nginx-deployment-basic
   jobs:
   - name: "scale-down"
     schedule: "0 50 8 * * 0,1,2,4,5"
     targetSize: 1
     runOnce: true
```
2. edit previous CronHorizontalPodAutoscaler
```
apiVersion: autoscaling.alibabacloud.com/v1beta1
kind: CronHorizontalPodAutoscaler
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cronhpa-sample
spec:
   scaleTargetRef:
      apiVersion: apps/v1beta2
      kind: Deployment
      name: nginx-deployment-basic
   jobs:
   - name: "scale-down"
     schedule: "0 59 8 * * 0,1,2,4,5"
     targetSize: 2
     runOnce: true
```

Cronhpa will finally reduce replicas to 1 at 16:50 Beijing time.
