### ISSUE TITLE
定时任务不生效

### ISSUE THREAD

**Issue by currycan** [AliyunContainerService/kubernetes-cronhpa-controller#30]
您好！
       按照步骤部署了环境，并用examples里面的例子运行了一下，按照整小时的任务不生效。如下：
```yaml
   jobs:
   - name: "scale-down"
     schedule: "30 52 17 * * *"
     targetSize: 2
   - name: "scale-up"
     schedule: "50 50 17 * * *"
     targetSize: 5
```
测试了下在17点50分50秒并没有进行扩容，52分30秒也没有缩容。但是如果是按整分钟没有问题：
```yaml
   jobs:
   - name: "scale-down"
     schedule: "30 58 * * * *"
     targetSize: 2
   - name: "scale-up"
     schedule: "50 56 * * * *"
     targetSize: 5
```
