### ISSUE TITLE
kubernetes-cronhpa-controller现在支持HPA了吗？？

### ISSUE THREAD

**Issue by vperson** [AliyunContainerService/kubernetes-cronhpa-controller#51]
之前使用的时候测试了HPA环境下面的伸缩发现有问题，现在kubernetes-cronhpa-controller 对HPA支持已经完善了吗？？？

**Comment by vperson** [comment]
这是我在HPA环境下的配置，运行后报错：

time="2020-04-24T02:50:40Z" level=info msg="&{{CronHorizontalPodAutoscaler autoscaling.alibabacloud.com/v1beta1} {cronhpa-app-mfs  dev1-xiaomai-server /apis/autoscaling.alibabacloud.com/v1beta1/namespaces/dev1-xiaomai-server/cronhorizontalpodautoscalers/cronhpa-app-mfs 23ff71b3-85d3-11ea-89cc-00163e0a57cb 380079424 1 2020-04-24 02:27:27 +0000 UTC <nil> <nil> map[controller-tools.k8s.io:1.0] map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"autoscaling.alibabacloud.com/v1beta1\",\"kind\":\"CronHorizontalPodAutoscaler\",\"metadata\":{\"annotations\":{},\"labels\":{\"controller-tools.k8s.io\":\"1.0\"},\"name\":\"cronhpa-app-mfs\",\"namespace\":\"dev1-xiaomai-server\"},\"spec\":{\"jobs\":[{\"name\":\"scale-down\",\"runOnce\":true,\"schedule\":\"* */10 * * * *\",\"targetSize\":1},{\"name\":\"scale-up\",\"runOnce\":true,\"schedule\":\"* */20 * * * *\",\"targetSize\":3}],\"scaleTargetRef\":{\"apiVersion\":\"autoscaling/v2beta1\",\"kind\":\"HorizontalPodAutoscaler\",\"name\":\"dev1-app-mfs-latest\"}}}\n] [] nil []  []} {{autoscaling/v2beta1 HorizontalPodAutoscaler dev1-app-mfs-latest} [{scale-down * */10 * * * * 1} {scale-up * */20 * * * * 3}]} {[{scale-up 1d9497c6-3ba9-43b2-8c31-6019581751bf * */20 * * * * Submitted 2020-04-24 02:48:18 +0000 UTC } {scale-down f154bb9c-98a5-47a1-8233-7c0e1f05e9ef * */10 * * * * Failed 2020-04-24 02:50:40 +0000 UTC cron hpa failed to execute,because of Failed to found source target dev1-app-mfs-latest}]}} has been handled completely."

**Comment by ringtail** [comment]
`because of Failed to found source target dev1-app-mfs-latest` 这个HPA对象存在吗

**Comment by ringtail** [comment]
cronhpa和hpa是在同一个namespace吗

**Comment by ringtail** [comment]
另外cronhpa的版本是现在最新的版本吗

**Comment by vperson** [comment]
在同一个namespace中。

这是我的详细配置：
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: app-mfs
  namespace: dev1-xiaomai-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev1-app-mfs-latest
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
    - resource:
        name: memory
        targetAverageUtilization: 90
      type: Resource

---
apiVersion: autoscaling.alibabacloud.com/v1beta1
kind: CronHorizontalPodAutoscaler
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cronhpa-app-mfs
  namespace: dev1-xiaomai-server
spec:
   scaleTargetRef:
      apiVersion: autoscaling/v2beta1
      kind: HorizontalPodAutoscaler
      name: app-mfs
   jobs:
   - name: "scale-down"
     schedule: "* */10 * * * *"
     targetSize: 1
     runOnce: false
   - name: "scale-up"
     schedule: "* */20 * * * *"
     targetSize: 3
     runOnce: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev1-app-mfs-latest
  namespace: dev1-xiaomai-server
  labels:
    app: app-mfs
    version: latest
spec:
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dev1-app-mfs
      version: latest
  template:
    metadata:
      labels:
        app: dev1-app-mfs
        version: latest
      annotations:
        prometheus.io/path: "prometheus"
        prometheus.io/port: "7004"
        prometheus.io/scrape: "false"
    spec:
      automountServiceAccountToken: false
.................
..................
```
