### ISSUE TITLE
hpa scheduling logic problem

### ISSUE THREAD

**Issue by ltm54250** [AliyunContainerService/kubernetes-cronhpa-controller#87]
I want to set a task with hpa,such as:

apiVersion: autoscaling.alibabacloud.com/v1beta1
kind: CronHorizontalPodAutoscaler
metadata:
  name: abc
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    name: abc
  jobs:
  - name: "scale-up"
    schedule: "0 0 8 * * *"
    targetSize: 3

When I set a hpa job(use cronhpa to adjust hpa) with cronhpa,I think most people want to set a minimum replica in order to keep the desired number of replica >= the minimum number of replica after a certain time.
Refer to the example above, I want to set replica >= 3 from 8 o'clock,I hope desired replica >= 3 from 8'oclock. But now if desired replica is 3 ,minimal replica is 2 at 8'oclock,cronhpa will skip schedule. Like this,after a while,if hpa metric value  is below the threshold,hpa will trigger shrink.
If shrink is happened,desired replica will be set to 2. But I hope desired replica >=3 from 8 o'clock.The schedule did not meet expectations.
In a word,I think cronhpa schedule should change state and keep it instead of changing the state at a time point.

I think，cronjob.go, under logic need change,

	if updateHPA {
		err = ch.client.Update(ctx, hpa)
		if err != nil {
			return "", err
		}
	}

	if hpa.Status.CurrentReplicas >= ch.DesiredSize {
		// skip change replicas and exit
		return fmt.Sprintf("Skip scale replicas because HPA %s current replicas:%d >= desired replicas:%d.", hpa.Name, scale.Spec.Replicas, ch.DesiredSize), nil
	}

should change to this:

	if hpa.Status.CurrentReplicas >= ch.DesiredSize {
		*hpa.Spec.MinReplicas = ch.DesiredSize
		updateHPA = true
	}

	if updateHPA {
		err = ch.client.Update(ctx, hpa)
		if err != nil {
			return "", err
		}
	}

**Comment by ringtail** [comment]
Why not set hpa min to 2?

**Comment by ltm54250** [comment]
For example, I need 2 - 6 replicas to achieve daily requirement after evaluation, so I set hpa between 2 and 6.  Duraing a low load period of Monday to Friday，2 replica can achieve my requirement, But I need 3 replica in a low load period of Saturday or Sunday. So I need use cronhpa to set min replica to 3 in  Saturday or Sunday.

So I think ，when we use cronhpa to adjust hpa, we don't need care desire replica. We should use hpa to set a min and max replica to achieve our requirement and  use cronhpa to set max or min replica of hpa. Hpa can auto set desired replica, we only need set min or max replica to hpa with cronhpa.

**Comment by ringtail** [comment]
@ltm54250 We will have a discussion about this issue.

**Comment by ringtail** [comment]
@ltm54250 I think we mix the effects with side effects together. Another filed to adjust hpa would be better. What's your opinion about it.

**Comment by ltm54250** [comment]
In my practice, I need and must use  hpa in all most all cases. So hpa should  deal with major schedule task. Cronhpa should assist hpa to deal with schedule task.  According to this, I think use cronhpa to adjust min and max is enough.

**Comment by ringtail** [comment]
What If you want to prepare 100 pods when you really need 50 to guarantee for the big sale.
HPA  min: 10 max:200 
CronHPA time1: 100 time2: 10

**Comment by ltm54250** [comment]
I must need to prepare enough pods in advance When I use cronhpa to adjust hpa.
If  i set hpa min to 100  with cronhpa, I think I must need 100 pods at the special time and continue a period.
The value 100  must be pre-assessed and It's not a waste.This period may be a peak of my business,I need 100 pods to keep business health. 
From the special  time and continue a period,I  need at least 100 pods,so I should set min to 100 not desire.
After this period, I can set hpa min to 10 with cronhpa.
For example, assuming from 20 o'clock on Saturday to 6 o'clock on Sunday  is  business peak period,I need 10 pods in this period,I only need 2 in other time.I can set
hpa:
min:2 max: 20
cronhpa:
----------------- 
min 10  
* * 20 * * 6
----------------
min 2
* * 6 * * 0

**Comment by jose-fully-ported** [comment]
Would it be possible to change this so that it sets the minimum pod count in an associated HPA to the `targetSize`? For example:

```
apiVersion: autoscaling.alibabacloud.com/v1beta1
kind: CronHorizontalPodAutoscaler
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cronhpa-sample
  namespace: default 
spec:
   scaleTargetRef:
      apiVersion: apps/v1beta2
      kind: Deployment
      name: nginx-deployment-basic
   jobs:
   - name: "scale-down"
     schedule: "30 */1 * * * *"
     targetSize: 1
     hpa: hpa-sample
     hpaField: minReplicas
   - name: "scale-up"
     schedule: "0 */1 * * * *"
     targetSize: 3
     hpa: hpa-sample
     hpaField: minReplicas
```

If the `hpaField` is not set, nothing would happen. The `hpa` name would be required, and the `namespace` of the hpa would be the namespace of the `CronHorizontalPodAutoscaler`.
